[package]
name = "ml_sample"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smartcore  = "0.2.0"
hello = {path = "./hello"} # 追加

# [dependencies.hello]
# path = "./hello"